spring.application.name=sewjo
spring.datasource.url=jdbc:postgresql://dpg-cq8tmrjv2p9s73cakncg-a.oregon-postgres.render.com/sewjo
spring.datasource.username=sewjo_user
spring.datasource.password=gkONd8wiMbJkkmMNVNJHbTqvUDbG925k
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.tomcat.accesslog.enabled=true