spring.application.name=login

server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-cq2tn2rqf0us73d72oi0-a.oregon-postgres.render.com/user_gbts
spring.datasource.username=user_gbts_user
spring.datasource.password=RrpleyGXED7YKZYh84zD2JsIuvZNwNcf
